version: '3.4'
services:
  app:
   image: busybox
   command: sh -c 'while true; do echo ''{\"hello\":\"world\"}''; sleep 1; done'
   depends_on:
     - logstash
   logging:
     driver: gelf
     options:
       gelf-address: udp://localhost:12201

  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"

  logstash:
    image: logstash:5.6.9
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
        - "12201:12201/udp"
    volumes:
        - "./logstash:/etc/logstash/conf.d"
    depends_on:
        - elasticsearch

  kibana:
    image: kibana:5.6.9
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"  
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200


  
